-- MySQL Script generated by MySQL Workbench
-- ven. 23 févr. 2018 11:36:27 CET
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`troupe`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`troupe` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL,
  `unitée` INT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`equipes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`equipes` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL,
  `troupe` VARCHAR(45) NULL,
  `troupe_ID` INT NOT NULL,
  PRIMARY KEY (`ID`, `troupe_ID`),
  INDEX `fk_equipes_troupe_idx` (`troupe_ID` ASC),
  CONSTRAINT `fk_equipes_troupe`
    FOREIGN KEY (`troupe_ID`)
    REFERENCES `mydb`.`troupe` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`epreuves`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`epreuves` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NULL,
  `boucle` VARCHAR(1) NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`equipes_has_epreuves`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`equipes_has_epreuves` (
  `equipes_ID` INT NOT NULL,
  `epreuves_ID` INT NOT NULL,
  `arrivee` DATETIME NULL,
  `depart` DATETIME NULL,
  `points` INT NULL,
  PRIMARY KEY (`equipes_ID`, `epreuves_ID`),
  INDEX `fk_equipes_has_epreuves_epreuves1_idx` (`epreuves_ID` ASC),
  INDEX `fk_equipes_has_epreuves_equipes1_idx` (`equipes_ID` ASC),
  CONSTRAINT `fk_equipes_has_epreuves_equipes1`
    FOREIGN KEY (`equipes_ID`)
    REFERENCES `mydb`.`equipes` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_equipes_has_epreuves_epreuves1`
    FOREIGN KEY (`epreuves_ID`)
    REFERENCES `mydb`.`epreuves` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
